### PR TITLE
fixes #9163 - create a 2nd service_wait provider for systemd

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Renamed the existing service_wait to service_wait_el6.  It didn't look like having both with the same name caused an issue, but i figured i'd be safe.  
Need to do a tad bit more testing, but opening for feedback.

**Comment by ehelms** [comment]
I might would split these into separate files as I *think* that tends to be more of the convention. A file named after the provider and a file per provider.

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
